README.md
pyrobuf/__main__.py
pyrobuf/parse_proto.py
pyrobuf/protobuf/templates/proto_pxd.tmpl
pyrobuf/protobuf/templates/proto_pyx.tmpl
pyrobuf/protobuf/templates/pyrobuf_list_pxd.tmpl
pyrobuf/protobuf/templates/pyrobuf_list_pyx.tmpl
tests/proto/test_is_initialized.proto
tests/proto/test_message_field_types.proto
tests/test_has_field.py
tests/test_is_initialized.py
tests/test_merge_from.py
tests/test_message_field_types.py
tests/test_message_init_kwargs.py

This PR addresses issue #16 and adds support for the following message methods:
- `Clear`
- `ClearField`
- `CopyFrom`
- `HasField`
- `IsInitialized`
- `MergeFrom`
- `MergeFromString`
- `SetInParent`
- `SerializePartialToString`
I have removed message validation from `ParseFromString` as it is not performed in protobuf's `ParseFromString` method. Also, message constructors and the `TypedList.add` method now support keyword arguments as protobuf's equivalents do.
Finally, this PR should also fix issue #8.

Add message methods

---

pyrobuf/setuptools_ext.py
setup.py

This should make it easier to install Pyrobuf. Currently, `pip install pyrobuf` will fail without the jinja2 and cython packages, with this change it seems to be succeeding for me in a clean virtualenv.
Jinja2 and Cython will be fetched automatically by setuptools; there are still gotchas with this approach (setuptools will use easy_install, which uses a different config file than pip, so people with private repos will need to be aware) but I think it's the best that can be done for now.

Use setup_requires for Jinja2 and Cython.

---

.gitignore
README.md
setup.py
tests/create_message.py
tests/test_issue_11.py
tests/test_message.py

Currently the pyrobuf setup.py script will add the `pyrobuf_list` and `pyrobuf_util` extension modules to the distribution configuration only when the setup.py `install` command is executed. This PR enhances the setup script to add the extension modules for every setup.py command. This means, for example, that one can use the command:
```
python setup.py build
```
to build (or rebuild) pyrobuf, or the command:
```
python setup.py develop
```
to install pyrobuf in editable mode.
Furthermore, this PR enhances the setup.py `clean` command to remove temporary artifacts created by the pyrobuf build process and ensures that setup.py honours the 'dry_run' and 'verbose' command line arguments.
Finally, this PR uses pytest fixtures to add the test build directory to the system path when running …

Add extension modules for every setup.py command

---

.gitignore
MANIFEST.in
pyrobuf/protobuf/templates/proto_pxd.tmpl
pyrobuf/protobuf/templates/proto_pyx.tmpl
setup.cfg
setup.py
tests/create_message.py
tests/performances.py
tests/proto_lib_fixture.py
tests/test_deprecated_field.py
tests/test_has_field.py
tests/test_imported_enums.py
tests/test_is_initialized.py
tests/test_issue_11.py
tests/test_lists.py
tests/test_merge_from.py
tests/test_message.py
tests/test_message_decimal_defaults.py
tests/test_message_field_types.py
tests/test_message_init_kwargs.py
tests/test_message_with_no_fields.py
tests/test_missing_lbraces.py
tests/test_string_defaults.py
tox.ini

This PR should address the issues raised in ticket #28. Pyrobuf now compiles and passes all current tests on both Python 2.7 and Python 3.5. I've added a tox.ini file so that [tox](https://testrun.org/tox/latest/) can be used to automatically test Pyrobuf on both versions.
One change worth noting is that `SerializeToString` and `SerialiazePartialToString` now return a string rather than a bytearray.

Fixes for python 3.5

---

pyrobuf/src/pyrobuf_util.pyx
tests/proto/test_signed_integer.proto
tests/test_signed_integer.py

Hi,
We are using pyrobuf to enhance performance in our project. The speed is fast but we noticed a problem in underlying operation when dealing with variant integers. : (
The current version of `set_signed_varint` will **hang**  sometimes since the right shift to a **negetive** integer will be -1 (the while clause will never terminate).  I have attached a randomized testing to reproduce the situation. As far as I know, the protobuf protocol uses zigtag algorithm to encode a signed value to an unsigned one. So I've made some change to the function (please refer to the code). : )
And a similar problem occurs in the `get_signed_varint` function. I guess we could use the following simple algorithm to decode a zigtag-encoded number back:
`(value >> 1) ^ (-(value & 1)`
Another obervation is …

Signed varint problem with zigzag encoding

---

pyrobuf/parse_proto.py
tests/test_syntax.py

This PR attempts to resolve #38.
If the syntax field is present it must be ``proto2``. This allows proto files with the optional syntax field present to continue parsing.
The included test performs simple checks for implicit and explicit declaration of ``syntax = "proto2";`` and checks for an exception being raised if any other proto version is encountered.

handle optional syntax field

---

README.md
pyrobuf/src/pyrobuf_util.pyx
tests/test_varint_encoding.py

This PR adds two new functions to pyrobuf_util:
- `from_varint(data, offset=0)` -- returns a (integer value, new offset) pair obtained by decoding the varint encoded integer in the supplied byte string beginning at the specified offset
- `from_signed_varint(data, offset=0)` -- returns a (integer value, new offset) pair obtained by decoding the signed-varint encoded integer in the supplied byte string beginning at the specified offset
I've also added some documentation to README.md concerning the `to_varint`, `to_signed_varint`, `from_varint` and `from_signed_varint` functions.

Fix #41: Add from_varint functions to pyrobuf_util

---

setup.py

Just ran into the following exception installing Pyrobuf on a dev server running Ubuntu 14.04:
```jinja2.exceptions.TemplateRuntimeError: no test named 'equalto'```
Noticed that the Jinja2 version was 2.7.2 versus 2.8.0 on my local machine and upgrading fixed the problem.

set minimum jinja2 version

---

README.md
pyrobuf/setuptools_ext.py

This PR removes a Python 2.7 incompatible reference to the 'exist_ok' keyword argument to `os.makedirs` in `setuptools_ext.py`. It also adds a new section to the README.md file documenting the `pyrobuf_modules` setup keyword with a simple example.

Fix Python 2.7 problem and document the pyrobuf_modules setup keyword 

---

pyrobuf/protobuf/templates/pyrobuf_list_pxd.tmpl
pyrobuf/protobuf/templates/pyrobuf_list_pyx.tmpl
tests/test_lists.py
tests/test_typed_lists.py

Previously the TypedList `extend` method would only work if given another TypedList (with the same list type) as an argument. Similarly the `extend` method of scalar lists would only work if given another scalar list of the same type. This PR makes the list extend methods work with any iterable as long as its elements are of the appropriate type.
This PR also fixes a subtle bug in the TypedList `extend` method which would cause the extended list to have references to the elements of the iterable rather than copies of them as the [protobuf semantics require](https://developers.google.com/protocol-buffers/docs/reference/python-generated#repeated-message-fields).

Fix #48. Support any iterable in list extend methods

---

pyrobuf/src/pyrobuf_util.pyx

Performance difference seems to be negligible, but no reason this should not be typed. Probably worth revisiting these functions entirely at some point.

add type to a local variable used in set_varint functions

---

pyrobuf/parse_proto.py

This was leading to a
```
AttributeError: 'ParserField' object has no attribute 'typ'
```

Minor parse_proto.py typo fix

---

pyrobuf/parse_proto.py
pyrobuf/protobuf/templates/proto_pxd.tmpl
pyrobuf/protobuf/templates/proto_pyx.tmpl
tests/proto/test_enum_conflicts.proto

Following on from @AndreMiras's [pull request 68 ](https://github.com/appnexus/pyrobuf/pull/68), this pull request causes pyrobuf to differentiate between nested enums with the same name. For example:
```protobuf
enum TestEnum {
TEST_VALUE = 1;
}
message TestMessage {
enum TestEnum {
TEST_VALUE = 1;
}
optional TestEnum test_field = 1;
}
message TestMessage2 {
optional TestEnum test_field = 1;
}
```

Differentiate between nested enums with the same names

---

pyrobuf/protobuf/templates/proto_pyx.tmpl
pyrobuf/src/pyrobuf_util.pxd
pyrobuf/src/pyrobuf_util.pyx
setup.py
tests/proto/test_truncated.proto
tests/test_unknown_field.py

Currently, if we encounter a key in a serialized message with an unknown index, we just ignore it and skip to the next byte, but this is incorrect; we actually need to skip over the size of the field.

Parse unrecognized fields to update offset correctly when deserializing

---

pyrobuf/setuptools_ext.py

I have fixed the problem with using `pyrobuf` in `setup.py`. I was failing because of changes in the `generate` function arguments.
Example:
```
Traceback (most recent call last):
File "setup.py", line 74, in <module>
author_email='chwalisz@tkn.tu-berlin.de'
File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
_setup_distribution = dist = klass(attrs)
File "/home/chwalisz/Code/package/.venv_temp/lib/python3.6/site-packages/setuptools/dist.py", line 318, in __init__
_Distribution.__init__(self, attrs)
File "/usr/lib/python3.6/distutils/dist.py", line 281, in __init__
self.finalize_options()
File "/home/chwalisz/Code/package/.venv_temp/lib/python3.6/site-packages/setuptools/dist.py", line 376, in finalize_options
ep.load()(self, ep.name, value)
File …
```

fixed setuptools extension

---

pyrobuf/parse_proto.py
pyrobuf/parse_proto3.py

When `parse_proto3` is imported `ParseField` and `ParseFieldDeprecated` don't override the default (`parse_proto`) implementation causing to write wrong implementation for repeated fields: `field.modifier` will hold `'repeated '` value instead `'repeated'`.

Unable to override class `ParserField` and `ParserFieldDeprecated` for proto3

---

pyrobuf/parse_proto.py
pyrobuf/protobuf/templates/proto_pxd.tmpl
pyrobuf/protobuf/templates/proto_pyx.tmpl
setup.py
tests/test_parser/test_field_validity.py
tests/test_parser/test_map_field.py
tests/test_parser/test_oneof.py

Raises an `AssertionError` on any of the following:
- Name collision between message fields
- Index collision between message fields
- Non-positive field index
- Name collision between enum fields
- Value collision between enum fields
- Nonzero default enum value (in proto3)
- Name collision between any names defined in the current scope
Other changes:
- Adds test cases for the above
- Adds `scope` argument to `_parse_enum` to expedite collision checking
- Takes a dict in the format of `{token.name: token, ...}` representing all names defined in the current scope (i.e. enum fields, message fields, and messages)
- Changes `Message.fields` and `Enum.fields` to dicts to expedite collision checking
- Key represents the index/value of each field
- Adds `Enum.default`
- Since dicts are …

Prevent name/index collisions

---

pyrobuf/setuptools_ext.py
setup.py

Current implementation fails both on Python 2.7 and Python 3.x
```
$ cat setup.py 
from setuptools import setup, find_packages
setup(
name="sample",
version="0.1",
packages=find_packages(),
description="A sample package",
install_requires=['pyrobuf'],
setup_requires=['pyrobuf'],
pyrobuf_modules="proto"
)
$ python setup.py install
generating p
Traceback (most recent call last):
File "setup.py", line 10, in <module>
pyrobuf_modules="proto"
File "/home/lauris/v4/sample/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
return distutils.core.setup(**attrs)
File "/usr/lib/python3.7/distutils/core.py", line 108, in setup
_setup_distribution = dist = klass(attrs)
File "/home/lauris/v4/sample/venv/lib/python3.7/site-packages/setuptools/dist.py", line 448, in __init__
k: …
```

Fix broken setuptools_ext

---

pyrobuf/compile.py

Fixed egg name not respecting a package name specified with the --package parameter and always defaulting to pyrobuf_generated.
Before this fix, a generated egg with: pyrobuf --install --package=mytest mytest.proto would yield an egg named "pyrobuf_generated.egg" instead of "mytest.egg"

Fixed generated egg name not respecting package name parameter

---

pyrobuf/protobuf/templates/proto_pyx.tmpl
setup.py
tests/proto/test_ref_message.proto
tests/test_float_field.py

Current implementation returns `bool` fields as `int`.
Protobuf specification implies it should be `bool` - https://developers.google.com/protocol-buffers/docs/proto3#json

Return bool fields as bool, not int
